# -*- coding: utf-8 -*-
"""producer_script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FdiG-fsH84jNAyaq-HEqZ72kkhJkEo_a
"""

import pandas as pd
from kafka import KafkaProducer
import json

# Read the CSV file into a DataFrame
file_path = '/tmp/data.csv'
df_without_header = pd.read_csv(file_path, encoding='latin1')

# Convert DataFrame to a list of dictionaries (each row is a dictionary)
df_dict = df_without_header.to_dict(orient='records')

# Set up Kafka producer
producer = KafkaProducer(
    bootstrap_servers='localhost:9092',
    value_serializer=lambda v: json.dumps(v).encode('utf-8')
)

try:
    # Publish data to Kafka topics based on Quantity
    for record in df_dict:
        quantity = record['Quantity']

        # Categorize transactions based on Quantity
        if quantity <= 3:
            topic = 'low_quantity'
        elif 3 < quantity <= 6:
            topic = 'medium_quantity'
        else:
            topic = 'high_quantity'

        # Send the record to the corresponding Kafka topic
        producer.send(topic, value=record)

    # Ensure all records are sent to Kafka before exiting
    producer.flush()

finally:
    # Close the Kafka producer
    producer.close()